name: github-demo-host
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: ${{ vars.CONJUR_URL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          authn_id: ${{ vars.CONJUR_AUTHN_ID }}
          secrets: ${{ vars.CONJUR_SECRETS }}
      - name : Echo USERNAME
        run: echo $SECRET1 | sed 's/./& /g'
      - name : Echo PASSWORD
        run: echo $SECRET2 | sed 's/./& /g'

      - name: Generate GitHub JWT
        id: generate_jwt
        run: |
          echo "Requesting GitHub JWT..."
          jwt=$(echo "${{ secrets.GITHUB_TOKEN }}" | \
            curl -s -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://token.actions.githubusercontent.com")

          echo "JWT Token:"
          echo "$jwt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}