name: github-demo-host
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for checkout
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    container:
      image: 5b9a49:15507546563f4ecaaf9c39f8af93760c
    steps:
      - run: bash ls -rtla
      - name : Echo USERNAME
        run: echo $SECRET1 | sed 's/./& /g'
      - name : Echo PASSWORD
        run: echo $SECRET2 | sed 's/./& /g'

      - name: Debug JWT
        run: |
          echo "Authenticate via Authn-JWT"
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
          JWT_TOKEN=$(curl -H "Authorization:bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r .value )
          echo $JWT_TOKEN | base64
