name: github-demo-host
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkouts
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: ${{ env.CONJUR_URL }}
          account: ${{ env.CONJUR_ACCOUNT }}
          authn_id: ${{ env.CONJUR_AUTHN_ID }}
          secrets: ${{ env.CONJUR_SECRETS }}
      - name : Echo USERNAME
        run: echo $SECRET1 | sed 's/./& /g'
      - name : Echo PASSWORD
        run: echo $SECRET2 | sed 's/./& /g'
